/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgVista;

import java.awt.Point;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pkgExcepciones.AeropuertoNombreExistenteException;
import pkgModelo.Aeropuerto;
import pkgModelo.Nodo;

/**
 * Clase que modela CreadorAeropuerto y hereda de JFrame
 * @author Juan C. Alvarez & Andres R. Alvarez
 */
public class CreadorAeropuerto extends JFrame {

    private PanelJuego padre;
    private Point posicionAeropuerto;
    private Nodo nodo;
    
    /**
     * Creates new form CreadorAeropuerto
     */
    public CreadorAeropuerto(PanelJuego padre, Nodo casillaAgregar) {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        setTitle("Agregar Aeropuerto");
        nodo = casillaAgregar;
        posicionAeropuerto = casillaAgregar.getPosicion();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.padre = padre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombreAeropuerto = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        chkAeroplano = new javax.swing.JCheckBox();
        chkPasajeros = new javax.swing.JCheckBox();
        chkCarga = new javax.swing.JCheckBox();
        chkHelicoptero = new javax.swing.JCheckBox();
        chkMilitar = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre del Aeropuerto:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Aeronaves admitidas:"));

        chkAeroplano.setText("Aeroplanos");

        chkPasajeros.setText("Aviones Comerciales de Transporte de Pasajeros");

        chkCarga.setText("Aviones Comerciales de Carga");

        chkHelicoptero.setText("Helicopteros");

        chkMilitar.setText("Aviones Militares");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkPasajeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkAeroplano, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkCarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkHelicoptero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkMilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAeroplano)
                    .addComponent(chkCarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkPasajeros)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(chkHelicoptero))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkMilitar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("OK!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreAeropuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreAeropuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean[] aterrizan = {chkAeroplano.isSelected(),chkCarga.isSelected(),chkPasajeros.isSelected(),chkHelicoptero.isSelected(),chkMilitar.isSelected()};
        if(!txtNombreAeropuerto.getText().equals(""))
        {
            if(aterrizan[0] || aterrizan[1] || aterrizan[2] || aterrizan[3] || aterrizan[4])
            {
                try {
                    Aeropuerto nuevo = new Aeropuerto(txtNombreAeropuerto.getText(), posicionAeropuerto, aterrizan, padre);
                    padre.getJuego().agregarAeropuerto(nuevo,nodo);
                    padre.repaint();
                    dispose();
                } catch (AeropuertoNombreExistenteException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Ya existe un aeropuerto con el nombre dado", JOptionPane.ERROR_MESSAGE);
                }
            }
            else
                JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un tipo de aeronave a permitir!", "Falta permiso aeronave", JOptionPane.ERROR_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre al aeropuerto!", "Falta nombre", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkAeroplano;
    private javax.swing.JCheckBox chkCarga;
    private javax.swing.JCheckBox chkHelicoptero;
    private javax.swing.JCheckBox chkMilitar;
    private javax.swing.JCheckBox chkPasajeros;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNombreAeropuerto;
    // End of variables declaration//GEN-END:variables

}