/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgVista;

import javax.swing.JFrame;
import pkgModelo.Juego;

/**
 * Clase que modela DefinirLineaLanzamiento y hereda de JFrame
 * @author Juan C. Alvarez & Andres R. Alvarez
 */
public class DefinirLineaLanzamiento extends JFrame {

    private Ventana padre;

    /**
     * Creates new form DefinirLineaLanzamiento
     */
    public DefinirLineaLanzamiento(Ventana padre) {
        initComponents();
  
        setTitle("Definir linea de lanzamiento");
        this.padre = padre;
        setLocationRelativeTo(null);

        comboLanzamiento.addItem("Norte");
        comboLanzamiento.addItem("Sur");
        comboLanzamiento.addItem("Este");
        comboLanzamiento.addItem("Oeste");
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboLanzamiento = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnOk.setText("OK!");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel1.setText("Elegir la orientación de lanzamiento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(comboLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(comboLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

        String seleccionado = (String) comboLanzamiento.getSelectedItem();
        if (seleccionado.equals("Norte")) {
            padre.getPanel().getJuego().setLineaSalida(Juego.NORTE);
        } else if (seleccionado.equals("Sur")) {
            padre.getPanel().getJuego().setLineaSalida(Juego.SUR);
        } else if (seleccionado.equals("Oeste")) {
            padre.getPanel().getJuego().setLineaSalida(Juego.OESTE);
        } else if (seleccionado.equals("Este")) {
            padre.getPanel().getJuego().setLineaSalida(Juego.ESTE);
        }
        padre.getBtnAgregarAeropuerto().setEnabled(true);
        padre.getBtnFinEdicion().setEnabled(true);
        padre.getBtnDefinirLineaLanzamiento().setEnabled(false);
        padre.getPanel().repaint();

        dispose();
    }//GEN-LAST:event_btnOkActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox comboLanzamiento;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
