/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgVista;

import java.io.File;
import java.io.FileNotFoundException;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JSlider;
import javax.swing.filechooser.FileNameExtensionFilter;
import pkgExcepciones.AeropuertoNombreExistenteException;
import pkgExcepciones.ArchivoNoValidoExcepion;
import pkgModelo.Espacio;
import pkgModelo.Juego;
import pkgModelo.ManejadorArchivos;

/**
 * Clase modela una Ventana que hereda de JFrame
 * @author Juan C. Alvarez & Andres R. Alvarez
 */
public class Ventana extends javax.swing.JFrame {

    private PanelJuego panel;
    private boolean editando;
    private DefinirLineaLanzamiento definirLineaLanzamiento;
    private ManejadorArchivos manejador;
    
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        
        manejador = new ManejadorArchivos();
        
        editando = false;
        
        panel = new PanelJuego(this);
        add(panel);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setResizable(false);
        setTitle("***** Juego Espacio Aereo *****");
        setSize(1285,685);
        
        ButtonGroup grupo = new ButtonGroup();
        grupo.add(radioManual);
        grupo.add(radioAutom);
        
        radioManual.setSelected(true);
        
        barraTiempo.setValue(3);
        lblPuntajeTotal.setText(""+panel.getJuego().getPuntajeTotal());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnCrearMapa = new javax.swing.JButton();
        btnCargarMapa = new javax.swing.JButton();
        btnAgregarAeropuerto = new javax.swing.JButton();
        btnFinEdicion = new javax.swing.JButton();
        btnDefinirLineaLanzamiento = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        radioManual = new javax.swing.JRadioButton();
        radioAutom = new javax.swing.JRadioButton();
        barraTiempo = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnIniciarJuego = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblTiempo = new javax.swing.JLabel();
        lblPuntajeTotal2 = new javax.swing.JLabel();
        lblPuntajeTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 204));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Mapa de juego"));

        btnCrearMapa.setText("CREAR MAPA");
        btnCrearMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMapaActionPerformed(evt);
            }
        });

        btnCargarMapa.setText("CARGAR MAPA");
        btnCargarMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarMapaActionPerformed(evt);
            }
        });

        btnAgregarAeropuerto.setText("AGREGAR AEROPUERTO");
        btnAgregarAeropuerto.setEnabled(false);
        btnAgregarAeropuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAeropuertoActionPerformed(evt);
            }
        });

        btnFinEdicion.setText(">> FIN EDICION");
        btnFinEdicion.setEnabled(false);
        btnFinEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinEdicionActionPerformed(evt);
            }
        });

        btnDefinirLineaLanzamiento.setText("Definir Linea de Lanzamiento");
        btnDefinirLineaLanzamiento.setEnabled(false);
        btnDefinirLineaLanzamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefinirLineaLanzamientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnCrearMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCargarMapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnDefinirLineaLanzamiento))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAgregarAeropuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFinEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDefinirLineaLanzamiento, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregarAeropuerto, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btnFinEdicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones de juego"));

        radioManual.setText("Control Manual");

        radioAutom.setText("Piloto Automático");

        barraTiempo.setMaximum(5);
        barraTiempo.setMinimum(3);
        barraTiempo.setPaintLabels(true);
        barraTiempo.setSnapToTicks(true);
        barraTiempo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                barraTiempoStateChanged(evt);
            }
        });

        jLabel1.setText("Tiempo de Juego (minutos):");

        jLabel2.setText("3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(radioManual, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioAutom, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(barraTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAutom)
                    .addComponent(radioManual))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnIniciarJuego.setText(">> INICIAR JUEGO <<");
        btnIniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarJuegoActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel3.setText("Tiempo Restante:");

        lblPuntajeTotal2.setText("Puntaje:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblPuntajeTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPuntajeTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPuntajeTotal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPuntajeTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnIniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIniciarJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 850, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barraTiempoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_barraTiempoStateChanged
        // TODO add your handling code here:
        jLabel2.setText(""+barraTiempo.getValue());
        panel.getJuego().getReloj().setMinuto(barraTiempo.getValue());
    }//GEN-LAST:event_barraTiempoStateChanged

    private void btnCrearMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMapaActionPerformed
        btnDefinirLineaLanzamiento.setEnabled(true);
        btnCargarMapa.setEnabled(false);
        btnCrearMapa.setEnabled(false); 
        panel.getJuego().setEspacio(new Espacio());
        panel.repaint();
    }//GEN-LAST:event_btnCrearMapaActionPerformed

    private void btnCargarMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarMapaActionPerformed
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de texto (*.txt)", "txt");
        JFileChooser jfc = new JFileChooser();
        jfc.setFileFilter(filtro);
        jfc.setDialogTitle("Abrir archivo de texto de configuracion de mapa");
        int seleccion = jfc.showOpenDialog(this);
        if(seleccion == JFileChooser.APPROVE_OPTION)
        {
            try {
                File f = jfc.getSelectedFile();
                Juego config = manejador.cargarConfiguracion(f.getPath(), panel.getJuego());
                System.out.println("#lkfjhnklfhndjklf "+config.getAeropuertos());
                panel.setJuego(config);
                panel.repaint();
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "No se ha encontrado el archivo en la ruta especificada", "Archivo no encontrado!", JOptionPane.ERROR_MESSAGE);
            } catch (ArchivoNoValidoExcepion ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Archivo no valido!", JOptionPane.ERROR_MESSAGE);
            } catch (AeropuertoNombreExistenteException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Problema!", JOptionPane.ERROR_MESSAGE);
            }
        }
        btnFinEdicion.setEnabled(true);
    }//GEN-LAST:event_btnCargarMapaActionPerformed

    private void btnAgregarAeropuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAeropuertoActionPerformed
        panel.setAgregando(true);
    }//GEN-LAST:event_btnAgregarAeropuertoActionPerformed

    private void btnFinEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinEdicionActionPerformed
        btnAgregarAeropuerto.setEnabled(false);
        btnFinEdicion.setEnabled(false);
        btnCargarMapa.setEnabled(true);
        btnCrearMapa.setEnabled(true);
        panel.setAgregando(false);
    }//GEN-LAST:event_btnFinEdicionActionPerformed

    private void btnDefinirLineaLanzamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefinirLineaLanzamientoActionPerformed

        definirLineaLanzamiento = new DefinirLineaLanzamiento(this);
        
    }//GEN-LAST:event_btnDefinirLineaLanzamientoActionPerformed

    private void btnIniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarJuegoActionPerformed
        barraTiempo.setEnabled(false);
        btnCrearMapa.setEnabled(false);
        btnCargarMapa.setEnabled(false);
        seleccionarModoJuego();
        Thread j = new Thread(panel.getJuego());
        j.start();
    }//GEN-LAST:event_btnIniciarJuegoActionPerformed

    private void seleccionarModoJuego() {
        if(radioManual.isSelected())
            panel.getJuego().setPilotoAutomatico(false);
        else if(radioAutom.isSelected())
            panel.getJuego().setPilotoAutomatico(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider barraTiempo;
    private javax.swing.JButton btnAgregarAeropuerto;
    private javax.swing.JButton btnCargarMapa;
    private javax.swing.JButton btnCrearMapa;
    private javax.swing.JButton btnDefinirLineaLanzamiento;
    private javax.swing.JButton btnFinEdicion;
    private javax.swing.JButton btnIniciarJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblPuntajeTotal;
    private javax.swing.JLabel lblPuntajeTotal2;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JRadioButton radioAutom;
    private javax.swing.JRadioButton radioManual;
    // End of variables declaration//GEN-END:variables

    public PanelJuego getPanel(){
        return panel;
    }
    
    public JButton getBtnAgregarAeropuerto(){
        return btnAgregarAeropuerto;
    }
    
    public JButton getBtnFinEdicion() {
        return btnFinEdicion;
    }
    
    public JButton getBtnDefinirLineaLanzamiento() {
        return btnDefinirLineaLanzamiento;
    }

    public boolean isEditando() {
        return editando;
    }

    public void setEditando(boolean editando) {
        this.editando = editando;
    }

    public DefinirLineaLanzamiento getDefinirLineaLanzamiento() {
        return definirLineaLanzamiento;
    }

    public void setDefinirLineaLanzamiento(DefinirLineaLanzamiento definirLineaLanzamiento) {
        this.definirLineaLanzamiento = definirLineaLanzamiento;
    }

    public JButton getBtnCargarMapa() {
        return btnCargarMapa;
    }

    public void setBtnCargarMapa(JButton btnCargarMapa) {
        this.btnCargarMapa = btnCargarMapa;
    }

    public JButton getBtnCrearMapa() {
        return btnCrearMapa;
    }

    public void setBtnCrearMapa(JButton btnCrearMapa) {
        this.btnCrearMapa = btnCrearMapa;
    }

    public JButton getjButton3() {
        return btnIniciarJuego;
    }

    public void setjButton3(JButton jButton3) {
        this.btnIniciarJuego = jButton3;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return lblPuntajeTotal2;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.lblPuntajeTotal2 = jLabel4;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JPanel getjPanel4() {
        return jPanel4;
    }

    public void setjPanel4(JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    public JRadioButton getjRadioButton1() {
        return radioManual;
    }

    public void setjRadioButton1(JRadioButton jRadioButton1) {
        this.radioManual = jRadioButton1;
    }

    public JRadioButton getjRadioButton2() {
        return radioAutom;
    }

    public void setjRadioButton2(JRadioButton jRadioButton2) {
        this.radioAutom = jRadioButton2;
    }

    public JSlider getjSlider1() {
        return barraTiempo;
    }

    public void setjSlider1(JSlider jSlider1) {
        this.barraTiempo = jSlider1;
    }

    public JLabel getLblPuntaje() {
        return lblPuntajeTotal;
    }

    public void setLblPuntaje(JLabel lblPuntaje) {
        this.lblPuntajeTotal = lblPuntaje;
    }

    public JLabel getLblTiempo() {
        return lblTiempo;
    }

    public void setLblTiempo(JLabel lblTiempo) {
        this.lblTiempo = lblTiempo;
    }

    public JSlider getBarraTiempo() {
        return barraTiempo;
    }

    public void setBarraTiempo(JSlider barraTiempo) {
        this.barraTiempo = barraTiempo;
    }

    public JButton getBotArrancar() {
        return btnIniciarJuego;
    }

    public void setBotArrancar(JButton botArrancar) {
        this.btnIniciarJuego = botArrancar;
    }

    public JRadioButton getRadioAutom() {
        return radioAutom;
    }

    public void setRadioAutom(JRadioButton radioAutom) {
        this.radioAutom = radioAutom;
    }

    public JRadioButton getRadioManual() {
        return radioManual;
    }

    public void setRadioManual(JRadioButton radioManual) {
        this.radioManual = radioManual;
    }
    
}
